name: playtorrio_nuvio_addon
description: Stremio and Nuvio compatible HTTP stream scraper addon powered by PlayTorrio scrapers.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.2.2
  html: ^0.15.5
  crypto: ^3.0.6
  pointycastle: ^3.9.1
  flutter:
    path: shim/flutter
  shared_preferences:
    path: shim/shared_preferences

dev_dependencies:
  lints: ^3.0.0
