import 'package:flutter/material.dart';

class HardcodedChannel {
  final String id;
  final String name;
  final String short;
  final String category;
  final List<String> keywords;
  final List<String> exclude;
  final List<Color> gradient;
  final String? iconUrl;
  final String? backdropUrl;

  const HardcodedChannel({
    required this.id,
    required this.name,
    required this.short,
    required this.category,
    required this.keywords,
    this.exclude = const [],
    required this.gradient,
    this.iconUrl,
    this.backdropUrl,
  });
}

class HardcodedChannels {
  static bool matches(String streamName, List<String> keywords, [List<String>? exclude]) {
    final lower = streamName.toLowerCase();
    if (exclude != null && exclude.isNotEmpty) {
      for (final ex in exclude) {
        if (lower.contains(ex.toLowerCase())) return false;
      }
    }
    for (final kw in keywords) {
      final kwLower = kw.toLowerCase().trim();
      if (kwLower.isEmpty) continue;
      if (kwLower.length <= 3) {
        final regex = RegExp(r'(?:^|[^a-zA-Z0-9])' + RegExp.escape(kwLower) + r'(?:$|[^a-zA-Z0-9])');
        if (regex.hasMatch(lower)) return true;
      } else {
        if (lower.contains(kwLower)) return true;
      }
    }
    return false;
  }

  static HardcodedChannel? byId(String id) {
    try {
      return all.firstWhere((c) => c.id == id);
    } catch (_) {
      return null;
    }
  }

  static List<HardcodedChannel> byCategory(String category) {
    return all.where((c) => c.category.toLowerCase() == category.toLowerCase()).toList();
  }

  static const List<HardcodedChannel> all = [
    // ── COMBAT SPORTS ──
    HardcodedChannel(
      id: 'ufc',
      name: 'UFC Fight Pass',
      short: 'UFC',
      category: 'Combat',
      keywords: ['ufc', 'fight pass', 'mma', 'ultimate fighting'],
      gradient: [Color(0xFFD20A0A), Color(0xFF1A1A1A)],
      iconUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/UFC_Fight_Pass_Logo.svg/960px-UFC_Fight_Pass_Logo.svg.png',
      backdropUrl: 'https://cdn.dribbble.com/userupload/44509326/file/1146907b6c2959c0a12c65d7259a58b6.png',
    ),
    HardcodedChannel(
      id: 'wwe',
      name: 'WWE Network',
      short: 'WWE',
      category: 'Combat',
      keywords: ['wwe', 'raw', 'smackdown', 'nxt', 'wrestlemania', 'wrestling'],
      gradient: [Color(0xFFCC0000), Color(0xFF000000)],
      iconUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/WWE_Network_logo.svg/500px-WWE_Network_logo.svg.png',
    ),
    HardcodedChannel(
      id: 'aew',
      name: 'All Elite Wrestling',
      short: 'AEW',
      category: 'Combat',
      keywords: ['aew', 'dynamite', 'rampage', 'collision', 'all elite'],
      gradient: [Color(0xFFC59B27), Color(0xFF1E1E1E)],
      iconUrl: 'https://i.imgur.com/5YO1phG.png',
    ),
    HardcodedChannel(
      id: 'boxing',
      name: 'World Boxing TV',
      short: 'BOX',
      category: 'Combat',
      keywords: ['boxing', 'boxnation', 'top rank', 'matchroom', 'pbc', 'golden boy'],
      gradient: [Color(0xFFB8860B), Color(0xFF2F4F4F)],
      iconUrl: 'https://i.imgur.com/XCIBf7u.png',
    ),
    HardcodedChannel(
      id: 'bellator',
      name: 'Bellator MMA',
      short: 'BEL',
      category: 'Combat',
      keywords: ['bellator', 'mma', 'pfl', 'mixed martial'],
      gradient: [Color(0xFFE65100), Color(0xFF212121)],
      iconUrl: 'https://i.imgur.com/VBKoLHk.png',
    ),
    HardcodedChannel(
      id: 'ppv_events',
      name: 'PPV Main Event',
      short: 'PPV',
      category: 'Combat',
      keywords: ['ppv', 'pay per view', 'box office', 'ppv event', 'ppv live', 'main event ppv'],
      exclude: ['sky sports', 'sky sport', 'bt sport', 'tnt sports'],
      gradient: [Color(0xFF9C27B0), Color(0xFF1A237E)],
      iconUrl: 'https://upload.wikimedia.org/wikipedia/en/e/e4/Main-event-au_logo.png',
    ),
    HardcodedChannel(
      id: 'one_championship',
      name: 'ONE Championship',
      short: 'ONE',
      category: 'Combat',
      keywords: ['one championship', 'one fc', 'muay thai', 'kickboxing'],
      gradient: [Color(0xFF00ACC1), Color(0xFF263238)],
      iconUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/singapore/one-championship-sg.png',
      backdropUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/singapore/one-championship-sg.png',
    ),

    // ── MOTORSPORT & RACING ──
    HardcodedChannel(
      id: 'f1',
      name: 'Formula 1 TV',
      short: 'F1',
      category: 'Racing',
      keywords: ['f1', 'formula 1', 'formula one', 'f1 tv', 'grand prix', 'sky f1', 'fia'],
      gradient: [Color(0xFFE10600), Color(0xFF15151E)],
      iconUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/Sky_Sport_F1_-_Logo_2020.svg/960px-Sky_Sport_F1_-_Logo_2020.svg.png',
      backdropUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSSVqWT4V4T7Fup-rDDuJE80yKhdI4UJ8pvY7G-ACH-ihehjdkziDI03GA&s=10',
    ),
    HardcodedChannel(
      id: 'motogp',
      name: 'MotoGP',
      short: 'MOTO',
      category: 'Racing',
      keywords: ['motogp', 'moto gp', 'moto2', 'moto3', 'motorcycle racing'],
      gradient: [Color(0xFF006699), Color(0xFF1C1C1C)],
      iconUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/international/motogp.png',
      backdropUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/international/motogp.png',
    ),
    HardcodedChannel(
      id: 'nascar',
      name: 'NASCAR Cup Series',
      short: 'NASC',
      category: 'Racing',
      keywords: ['nascar', 'cup series', 'xfinity', 'daytona', 'stock car'],
      gradient: [Color(0xFFFFD700), Color(0xFF002B49)],
      iconUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/usa/nascar-us.png',
      backdropUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/usa/nascar-us.png',
    ),
    HardcodedChannel(
      id: 'indycar',
      name: 'IndyCar Series',
      short: 'INDY',
      category: 'Racing',
      keywords: ['indycar', 'indy 500', 'indianapolis', 'open wheel'],
      gradient: [Color(0xFFD32F2F), Color(0xFF1A237E)],
      iconUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/usa/indycar-us.png',
      backdropUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/usa/indycar-us.png',
    ),
    HardcodedChannel(
      id: 'wrc',
      name: 'World Rally Championship (WRC)',
      short: 'WRC',
      category: 'Racing',
      keywords: ['wrc', 'rally', 'world rally', 'fia rally'],
      gradient: [Color(0xFFFF6D00), Color(0xFF37474F)],
      iconUrl: 'https://upload.wikimedia.org/wikipedia/commons/9/9c/WRC.svg',
    ),
HardcodedChannel(
      id: 'wsbk',
      name: 'World Superbike (WSBK)',
      short: 'WSBK',
      category: 'Racing',
      keywords: ['wsbk', 'world superbike', 'superbike', 'fim'],
      gradient: [Color(0xFFC2185B), Color(0xFF212121)],
      iconUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/international/wsbk.png',
      backdropUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/international/wsbk.png',
    ),

    // ── FOOTBALL & SOCCER ──
    HardcodedChannel(
      id: 'champions_league',
      name: 'UEFA Champions League',
      short: 'UCL',
      category: 'Soccer',
      keywords: ['champions league', 'ucl', 'uefa', 'europa league', 'conference league'],
      gradient: [Color(0xFF001489), Color(0xFF00083A)],
      iconUrl: 'https://i.imgur.com/BzQphbw.png',
      backdropUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSKIVxbksY0xMHuE2bdQlwr_8QgHstejx_mlCCF-m3VIR5m3EAKXHdQbek&s=10',
    ),
    HardcodedChannel(
      id: 'premier_league',
      name: 'Premier League',
      short: 'EPL',
      category: 'Soccer',
      keywords: ['premier league', 'epl', 'english premier', 'pl tv'],
      gradient: [Color(0xFF38003C), Color(0xFF00FF87)],
      iconUrl: 'https://upload.wikimedia.org/wikipedia/en/thumb/f/f2/Premier_League_Logo.svg/1024px-Premier_League_Logo.svg.png',
    ),
    HardcodedChannel(
      id: 'bein_sports',
      name: 'beIN Sports HD',
      short: 'beIN',
      category: 'Soccer',
      keywords: ['bein', 'bein sports', 'bein 1', 'bein 2', 'bein 3', 'bein 4', 'bein sport'],
      gradient: [Color(0xFF5C2D91), Color(0xFF1E1035)],
      iconUrl: 'https://i.imgur.com/RLrMBlm.png',
      backdropUrl: 'https://www.venclikovi.com/wp-content/uploads/2025/10/bein-sports-logo-global-streaming.webp',
    ),
    HardcodedChannel(
      id: 'sky_sports',
      name: 'Sky Sports Main Event',
      short: 'SKY',
      category: 'Soccer',
      keywords: ['sky sports', 'sky sports football', 'sky sports premier', 'sky sports main', 'sky sports news'],
      gradient: [Color(0xFF001965), Color(0xFFE60000)],
      iconUrl: 'https://cdn.skymedia.ie/wp-content/uploads/sites/4/2020/11/Sky-Sports-ME-2020-logo-250.png',
    ),
    HardcodedChannel(
      id: 'tnt_sports',
      name: 'TNT Sports HD',
      short: 'TNT',
      category: 'Soccer',
      keywords: ['tnt sports', 'tnt sport', 'bt sport', 'tnt 1', 'tnt 2', 'tnt 3'],
      gradient: [Color(0xFFE50000), Color(0xFF1A1A1A)],
      iconUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/TNT_Sports_2021_logo.svg/960px-TNT_Sports_2021_logo.svg.png',
    ),
    HardcodedChannel(
      id: 'la_liga',
      name: 'LaLiga TV HD',
      short: 'LALIGA',
      category: 'Soccer',
      keywords: ['laliga', 'la liga', 'laliga tv', 'spanish league', 'el clasico'],
      gradient: [Color(0xFF101820), Color(0xFFFF4B44)],
      iconUrl: 'https://i.imgur.com/ilay5Jr.png',
    ),
    HardcodedChannel(
      id: 'serie_a',
      name: 'Serie A TV',
      short: 'SERIE',
      category: 'Soccer',
      keywords: ['serie a', 'calcio', 'italian league', 'serie a pass'],
      gradient: [Color(0xFF003366), Color(0xFF0066CC)],
      iconUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Serie_A_logo_2019.svg/1024px-Serie_A_logo_2019.svg.png',
    ),
    HardcodedChannel(
      id: 'bundesliga',
      name: 'Bundesliga TV',
      short: 'BUND',
      category: 'Soccer',
      keywords: ['bundesliga', 'german league', 'bundesliga 1', 'bundesliga 2'],
      gradient: [Color(0xFFD3010C), Color(0xFF1A1A1A)],
      iconUrl: 'https://upload.wikimedia.org/wikipedia/en/thumb/d/df/Bundesliga_logo_%282017%29.svg/1024px-Bundesliga_logo_%282017%29.svg.png',
    ),
    HardcodedChannel(
      id: 'ligue_1',
      name: 'Ligue 1 Pass',
      short: 'L1',
      category: 'Soccer',
      keywords: ['ligue 1', 'french league', 'ligue 1 mcdonald', 'ligue 1 uber'],
      gradient: [Color(0xFF091C3E), Color(0xFF5EE8B7)],
      iconUrl: 'https://i.imgur.com/PtzoOQL.png',
    ),
    HardcodedChannel(
      id: 'mls',
      name: 'MLS Season Pass',
      short: 'MLS',
      category: 'Soccer',
      keywords: ['mls', 'major league soccer', 'mls pass'],
      gradient: [Color(0xFF002B49), Color(0xFFCC0000)],
      iconUrl: 'https://i.imgur.com/S2pBerQ.png',
    ),
    HardcodedChannel(
      id: 'world_cup',
      name: 'FIFA World Cup',
      short: 'FIFA',
      category: 'Soccer',
      keywords: ['fifa', 'world cup', 'fifa plus', 'fifa+'],
      gradient: [Color(0xFF005696), Color(0xFF00A3E0)],
      iconUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/FIFA%2B_(2025).svg/960px-FIFA%2B_(2025).svg.png',
    ),
    HardcodedChannel(
      id: 'copa_libertadores',
      name: 'Copa Libertadores',
      short: 'LIB',
      category: 'Soccer',
      keywords: ['libertadores', 'copa libertadores', 'conmebol', 'copa sudamericana'],
      gradient: [Color(0xFFD4AF37), Color(0xFF1A1A1A)],
      iconUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/CONMEBOL_Libertadores_logo.svg/1024px-CONMEBOL_Libertadores_logo.svg.png',
    ),
    HardcodedChannel(
      id: 'beout_q',
      name: 'SuperSport HD',
      short: 'SUPER',
      category: 'Soccer',
      keywords: ['supersport', 'super sport', 'dstv', 'supersport premier', 'supersport football'],
      gradient: [Color(0xFF005BA6), Color(0xFFD31145)],
      iconUrl: 'https://i.imgur.com/KXdVDis.png',
    ),

    // ── US SPORTS & NETWORKS ──
    // ── ESPN & COLLEGE SPORTS / BASKETBALL ──
    HardcodedChannel(
      id: 'espn',
      name: 'ESPN HD',
      short: 'ESPN',
      category: 'Sports',
      keywords: ['espn hd', 'espn 1', 'espn live', 'espn usa', 'espn us', 'espn main', 'espn east', 'espn west', 'espn 1080'],
      exclude: ['espn2', 'espn 2', 'espnu', 'espn u', 'espn+', 'espn plus', 'espn news', 'espnews', 'espn deportes', 'sec', 'acc'],
      gradient: [Color(0xFFCC0000), Color(0xFF1A1A1A)],
      iconUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/ESPN_wordmark.svg/960px-ESPN_wordmark.svg.png',
      backdropUrl: 'https://disney.images.edge.bamgrid.com/ripcut-delivery/v2/variant/espn/0EED69F98BADBE7F760C4F96CED05B20C7992B56AF98DD17A1E9BD18F128FD8E/compose?format=webp&width=2560',
    ),
    HardcodedChannel(
      id: 'espn_plus',
      name: 'ESPN+ Live Events & Exclusives',
      short: 'ESPN+',
      category: 'Sports',
      keywords: [
        'espn+',
        'espn plus',
        'espnplus',
        'espn +',
        'espn-plus',
        'espn+ 1',
        'espn+ 2',
        'espn+ 3',
        'espn+ 4',
        'espn+ 5',
        'espn+ 6',
        'espn+ 7',
        'espn+ 8',
        'espn+ 9',
        'espn+ 10',
        'espn+ event',
        'espn+ live',
        'espn plus 1',
        'espn plus 2',
        'espn plus 3',
        'espn plus 4',
        'espn plus 5',
        'espn+ stream',
      ],
      gradient: [Color(0xFF003087), Color(0xFFCC0000)],
      iconUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/ESPN%2B_logo.svg/1024px-ESPN%2B_logo.svg.png',
      backdropUrl: 'https://cdn.dribbble.com/userupload/10398604/file/original-d1c95ee13c1c9c7f1a30ff76b2f7dd4e.png',
    ),
    HardcodedChannel(
      id: 'espn2',
      name: 'ESPN2 HD',
      short: 'ESPN2',
      category: 'Sports',
      keywords: ['espn 2', 'espn2', 'espn 2 hd', 'espn2 hd', 'espn 2 usa', 'espn 2 live'],
      gradient: [Color(0xFFCC0000), Color(0xFF003087)],
      iconUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/ESPN2_wordmark.svg/1024px-ESPN2_wordmark.svg.png',
    ),
    HardcodedChannel(
      id: 'espnu',
      name: 'ESPNU (College Sports)',
      short: 'ESPNU',
      category: 'Sports',
      keywords: ['espnu', 'espn u', 'espnu hd', 'espn u hd', 'espn university', 'espn college'],
      gradient: [Color(0xFFCC0000), Color(0xFF000000)],
      iconUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/ESPNU_logo.svg/1024px-ESPNU_logo.svg.png',
    ),
    HardcodedChannel(
      id: 'espnews',
      name: 'ESPNews HD',
      short: 'NEWS',
      category: 'Sports',
      keywords: ['espnews', 'espn news', 'espnews hd', 'espn news hd'],
      gradient: [Color(0xFF8B0000), Color(0xFF1C1C1C)],
      iconUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/ESPNews_logo.svg/1024px-ESPNews_logo.svg.png',
    ),
    HardcodedChannel(
      id: 'espn_deportes',
      name: 'ESPN Deportes',
      short: 'DEP',
      category: 'Sports',
      keywords: ['espn deportes', 'espndeportes', 'espn deportes hd'],
      gradient: [Color(0xFFCC0000), Color(0xFFD4AF37)],
      iconUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/ESPN_Deportes_logo.svg/1024px-ESPN_Deportes_logo.svg.png',
    ),
    HardcodedChannel(
      id: 'sec_network',
      name: 'SEC Network & SEC+',
      short: 'SEC',
      category: 'Sports',
      keywords: ['sec network', 'secn', 'sec network+', 'sec network +', 'sec network plus', 'sec alt', 'sec alternate', 'sec hd'],
      gradient: [Color(0xFF002D62), Color(0xFFFFD100)],
      iconUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/SEC_Network_logo.svg/1024px-SEC_Network_logo.svg.png',
    ),
    HardcodedChannel(
      id: 'acc_network',
      name: 'ACC Network & ACCNX',
      short: 'ACC',
      category: 'Sports',
      keywords: ['acc network', 'accn', 'acc network+', 'acc network +', 'acc network plus', 'acc extra', 'accx', 'acc hd'],
      gradient: [Color(0xFF013CA6), Color(0xFF9FA1A4)],
      iconUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/ACC_Network_logo.svg/1024px-ACC_Network_logo.svg.png',
    ),
    HardcodedChannel(
      id: 'longhorn_network',
      name: 'Longhorn Network (LHN)',
      short: 'LHN',
      category: 'Sports',
      keywords: ['longhorn network', 'longhorn', 'lhn', 'texas longhorns'],
      gradient: [Color(0xFFBF5700), Color(0xFF333F48)],
      iconUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Longhorn_Network_logo.svg/1024px-Longhorn_Network_logo.svg.png',
    ),

    // ── COLLEGE BASKETBALL & CONFERENCES ──
    HardcodedChannel(
      id: 'ncaa_cbb',
      name: 'NCAA College Basketball (CBB Hub)',
      short: 'CBB',
      category: 'Sports',
      keywords: [
        'ncaa basketball',
        'college basketball',
        'ncaab',
        'ncaaw',
        'march madness',
        'ncaa tournament',
        'cbb live',
        'ncaa cbb',
        'mens basketball',
        'womens basketball',
        "men's basketball",
        "women's basketball",
        'ncaa hoops',
        'college hoops',
      ],
      gradient: [Color(0xFF005696), Color(0xFFFF6600)],
      iconUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/NCAA_logo.svg/1024px-NCAA_logo.svg.png',
      backdropUrl: 'https://images.axios.com/7bC4iF4p6321gqE76uW_wV5w06M=/0x0:1920x1080/1920x1080/2024/03/18/1710777558778.jpg',
    ),
    HardcodedChannel(
      id: 'ncaa_mens_cbb',
      name: "NCAA Men's Basketball (NCAAM)",
      short: 'NCAAM',
      category: 'Sports',
      keywords: [
        'ncaa men',
        "men's basketball",
        'ncaab',
        'ncaa mens basketball',
        'ncaa division 1 men',
        'cbb men',
        'mens college basketball',
        'march madness men',
        'ncaa d1 men',
        'ncaam',
        'ncaam basketball',
      ],
      gradient: [Color(0xFF003366), Color(0xFFC9082A)],
      iconUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/NCAA_logo.svg/1024px-NCAA_logo.svg.png',
    ),
    HardcodedChannel(
      id: 'ncaa_womens_cbb',
      name: "NCAA Women's Basketball (NCAAW)",
      short: 'NCAAW',
      category: 'Sports',
      keywords: [
        'ncaa women',
        "women's basketball",
        'ncaaw',
        'ncaa womens basketball',
        'ncaa division 1 women',
        'wbb',
        'womens college basketball',
        'march madness women',
        'wncaab',
        'ncaa d1 women',
        'ncaaw live',
        'ncaaw basketball',
      ],
      gradient: [Color(0xFF6B1D78), Color(0xFF008080)],
      iconUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/NCAA_logo.svg/1024px-NCAA_logo.svg.png',
    ),
    HardcodedChannel(
      id: 'big_ten_network',
      name: 'Big Ten Network (BTN & BTN+)',
      short: 'BTN',
      category: 'Sports',
      keywords: ['big ten network', 'btn', 'big 10 network', 'big ten', 'btn+', 'btn plus', 'big 10', 'btn hd'],
      gradient: [Color(0xFF003087), Color(0xFF000000)],
      iconUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/Big_Ten_Network_2020_Logo.svg/1024px-Big_Ten_Network_2020_Logo.svg.png',
    ),
    HardcodedChannel(
      id: 'pac_12_network',
      name: 'Pac-12 Network',
      short: 'PAC12',
      category: 'Sports',
      keywords: [
        'pac-12',
        'pac 12',
        'pac-12 network',
        'pac 12 network',
        'pac-12 bay area',
        'pac-12 los angeles',
        'pac-12 mountain',
        'pac-12 oregon',
        'pac-12 washington',
        'pac-12 arizona',
        'pac 12 national',
      ],
      gradient: [Color(0xFF004B87), Color(0xFF002244)],
      iconUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Pac-12_Network_Logo.svg/1024px-Pac-12_Network_Logo.svg.png',
    ),
    HardcodedChannel(
      id: 'bally_sports',
      name: 'FanDuel / Bally Sports HD',
      short: 'FDSN',
      category: 'Sports',
      keywords: [
        'fanduel sports',
        'bally sports',
        'bally sports south',
        'bally sports midwest',
        'bally sports sun',
        'bally sports florida',
        'bally sports detroit',
        'bally sports ohio',
        'bally sports west',
        'bally sports socal',
        'bally sports north',
        'bally sports wisconsin',
        'bally sports southwest',
        'bally sports southeast',
        'bally sports indiana',
      ],
      gradient: [Color(0xFF0D1B2A), Color(0xFF1B4965)],
      iconUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/FanDuel_Sports_Network_logo.svg/1024px-FanDuel_Sports_Network_logo.svg.png',
    ),
    HardcodedChannel(
      id: 'fox_sports',
      name: 'FOX Sports 1 (FS1)',
      short: 'FOX',
      category: 'Sports',
      keywords: ['fox sports', 'fs1', 'fs2', 'fox sports 1', 'fox sports 2', 'fox soccer'],
      gradient: [Color(0xFF003366), Color(0xFF0066CC)],
      iconUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/FOX_Deportes_logo.png/960px-FOX_Deportes_logo.png',
    ),
    HardcodedChannel(
      id: 'nbc_sports',
      name: 'NBC Sports',
      short: 'NBC',
      category: 'Sports',
      keywords: ['nbc sports', 'nbcsn', 'peacock sports', 'nbc golf'],
      gradient: [Color(0xFF0078D7), Color(0xFF2C3E50)],
      iconUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/NBCSN_logo_%28flat%29.svg/960px-NBCSN_logo_%28flat%29.svg.png',
    ),
    HardcodedChannel(
      id: 'cbs_sports',
      name: 'CBS Sports Network',
      short: 'CBS',
      category: 'Sports',
      keywords: ['cbs sports', 'cbssn', 'cbs sports network', 'paramount sports'],
      gradient: [Color(0xFF002244), Color(0xFF005596)],
      iconUrl: 'https://i.imgur.com/q8BENJg.png',
    ),
    HardcodedChannel(
      id: 'nba',
      name: 'NBA TV HD',
      short: 'NBA',
      category: 'Sports',
      keywords: ['nba tv', 'nba league pass', 'nba hd', 'basketball'],
      gradient: [Color(0xFF17408B), Color(0xFFC9082A)],
      iconUrl: 'https://i.imgur.com/Bwv5KgE.png',
      backdropUrl: 'https://m.media-amazon.com/images/S/sonata-images-prod/US_CHANNELS_NBATV_SeasonKickoff_1019/497224e7-8ed5-4063-b9c4-33ec7a46fa20._UR1920,1080_.jpeg',
    ),
    HardcodedChannel(
      id: 'nfl',
      name: 'NFL Network',
      short: 'NFL',
      category: 'Sports',
      keywords: ['nfl network', 'nfl game pass', 'nfl sunday ticket', 'nfl hd', 'american football'],
      gradient: [Color(0xFF013369), Color(0xFFD50A0A)],
      iconUrl: 'https://upload.wikimedia.org/wikipedia/en/thumb/8/8f/NFL_Network_logo.svg/960px-NFL_Network_logo.svg.png',
    ),
    HardcodedChannel(
      id: 'nfl_redzone',
      name: 'NFL RedZone',
      short: 'RED',
      category: 'Sports',
      keywords: ['nfl redzone', 'redzone', 'red zone', 'nfl red zone'],
      gradient: [Color(0xFFD50A0A), Color(0xFF013369)],
      iconUrl: 'https://i.imgur.com/5lPqQj5.png',
    ),
    HardcodedChannel(
      id: 'nhl',
      name: 'NHL Network',
      short: 'NHL',
      category: 'Sports',
      keywords: ['nhl network', 'nhl center ice', 'nhl hd', 'ice hockey', 'stanley cup'],
      gradient: [Color(0xFF000000), Color(0xFF003366)],
      iconUrl: 'https://i.imgur.com/UNZ8bef.png',
    ),
    HardcodedChannel(
      id: 'mlb',
      name: 'MLB Network',
      short: 'MLB',
      category: 'Sports',
      keywords: ['mlb network', 'mlb extra innings', 'mlb hd', 'baseball', 'world series'],
      gradient: [Color(0xFF002D62), Color(0xFFBA0C2F)],
      iconUrl: 'https://i.imgur.com/ym3su2J.png',
    ),
    HardcodedChannel(
      id: 'dazn',
      name: 'DAZN 1 HD',
      short: 'DAZN',
      category: 'Sports',
      keywords: ['dazn', 'dazn 1', 'dazn 2', 'dazn combat', 'dazn boxing'],
      gradient: [Color(0xFFF8F8F8), Color(0xFF1E1E1E)],
      iconUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/DAZN_1.svg/500px-DAZN_1.svg.png',
    ),
    HardcodedChannel(
      id: 'eurosport',
      name: 'Eurosport 1 HD',
      short: 'EURO',
      category: 'Sports',
      keywords: ['eurosport', 'eurosport 1', 'eurosport 2', 'discovery sports'],
      gradient: [Color(0xFF002B49), Color(0xFF005696)],
      iconUrl: 'https://i.imgur.com/s4jDnJh.png',
    ),

    // ── MOVIES & PREMIUM ENTERTAINMENT ──
    HardcodedChannel(
      id: 'hbo',
      name: 'HBO HD',
      short: 'HBO',
      category: 'Movies',
      keywords: ['hbo', 'hbo 2', 'hbo signature', 'hbo comedy', 'hbo zone', 'hbo family', 'hbo max'],
      gradient: [Color(0xFF5C2D91), Color(0xFF1A1A1A)],
      iconUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/HBO_logo.svg/960px-HBO_logo.svg.png',
      backdropUrl: 'https://wallpapercat.com/w/full/8/2/d/1263212-1920x1080-desktop-1080p-hbo-background-image.jpg',
    ),
    HardcodedChannel(
      id: 'showtime',
      name: 'Showtime HD',
      short: 'SHO',
      category: 'Movies',
      keywords: ['showtime', 'sho 2', 'sho showcase', 'sho extreme', 'paramount with showtime'],
      gradient: [Color(0xFFCC0000), Color(0xFF1A1A1A)],
      iconUrl: 'https://i.imgur.com/Or0LKsu.png',
    ),
    HardcodedChannel(
      id: 'starz',
      name: 'Starz HD',
      short: 'STARZ',
      category: 'Movies',
      keywords: ['starz', 'starz edge', 'starz inblack', 'starz cinema', 'starz comedy'],
      gradient: [Color(0xFF000000), Color(0xFF2C3E50)],
      iconUrl: 'https://i.imgur.com/N7oSm4d.png',
    ),
    HardcodedChannel(
      id: 'cinemax',
      name: 'Cinemax HD',
      short: 'MAX',
      category: 'Movies',
      keywords: ['cinemax', 'moremax', 'actionmax', 'thrillermax', 'outermax'],
      gradient: [Color(0xFFFFD700), Color(0xFF1A1A1A)],
      iconUrl: 'https://i.imgur.com/cZWoJWD.png',
    ),
    HardcodedChannel(
      id: 'paramount',
      name: 'Paramount Network',
      short: 'PARA',
      category: 'Movies',
      keywords: ['paramount', 'paramount network', 'paramount channel'],
      gradient: [Color(0xFF006699), Color(0xFF1A1A1A)],
      iconUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Paramount_Network.svg/960px-Paramount_Network.svg.png',
    ),
    HardcodedChannel(
      id: 'amc',
      name: 'AMC HD',
      short: 'AMC',
      category: 'Movies',
      keywords: ['amc', 'amc plus', 'amc+', 'american movie classics'],
      gradient: [Color(0xFF8B0000), Color(0xFF1A1A1A)],
      iconUrl: 'https://i.imgur.com/yj8RNnG.png',
    ),
    HardcodedChannel(
      id: 'fx',
      name: 'FX HD',
      short: 'FX',
      category: 'Movies',
      keywords: ['fx', 'fxx', 'fxm', 'fx movie channel'],
      gradient: [Color(0xFF212121), Color(0xFF424242)],
      iconUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/usa/fx-us.png',
      backdropUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/usa/fx-us.png',
    ),
    HardcodedChannel(
      id: 'sky_cinema',
      name: 'Sky Cinema Premiere',
      short: 'SKY C',
      category: 'Movies',
      keywords: ['sky cinema', 'sky movies', 'sky premiere', 'sky action', 'sky comedy', 'sky scifi'],
      gradient: [Color(0xFF800020), Color(0xFF1A1A1A)],
      iconUrl: 'https://upload.wikimedia.org/wikipedia/en/thumb/1/18/Sky_Cinema_Premiere_2024_logo.svg/960px-Sky_Cinema_Premiere_2024_logo.svg.png',
    ),
    HardcodedChannel(
      id: 'osn_movies',
      name: 'OSN Movies Premiere',
      short: 'OSN M',
      category: 'Movies',
      keywords: ['osn movies', 'osn premiere', 'osn action', 'osn comedy', 'osn cinema'],
      gradient: [Color(0xFF9C27B0), Color(0xFF1A1A1A)],
      iconUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-arab-emirates/osn-movies-ae.png',
      backdropUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-arab-emirates/osn-movies-ae.png',
    ),

    // ── 24/7 GLOBAL NEWS ──
    HardcodedChannel(
      id: 'cnn',
      name: 'CNN International',
      short: 'CNN',
      category: 'News',
      keywords: ['cnn', 'cnn international', 'cnn news', 'cnn hd'],
      gradient: [Color(0xFFCC0000), Color(0xFF1A1A1A)],
      iconUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/CNN.svg/960px-CNN.svg.png',
    ),
    HardcodedChannel(
      id: 'bbc_news',
      name: 'BBC World News',
      short: 'BBC',
      category: 'News',
      keywords: ['bbc news', 'bbc world news', 'bbc world', 'bbc hd'],
      gradient: [Color(0xFFBB1919), Color(0xFF1A1A1A)],
      iconUrl: 'https://ltsk-cdn.s3.eu-west-1.amazonaws.com/jumpstart/Temp_Live/cdn/HLS/Channel/transparentImages/BBC-logo_2000_X_1125_Transparent.png',
    ),
    HardcodedChannel(
      id: 'fox_news',
      name: 'Fox News Channel',
      short: 'FNC',
      category: 'News',
      keywords: ['fox news', 'fox business', 'fnc', 'fox news hd'],
      gradient: [Color(0xFF003366), Color(0xFFCC0000)],
      iconUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Fox_News_Channel_logo.svg/960px-Fox_News_Channel_logo.svg.png',
    ),
    HardcodedChannel(
      id: 'msnbc',
      name: 'MSNBC News',
      short: 'MSNBC',
      category: 'News',
      keywords: ['msnbc', 'msnbc news', 'msnbc hd'],
      gradient: [Color(0xFF005696), Color(0xFF1A1A1A)],
      iconUrl: 'https://upload.wikimedia.org/wikipedia/commons/7/7f/MSNBC_2023.svg',
    ),
    HardcodedChannel(
      id: 'sky_news',
      name: 'Sky News HD',
      short: 'SKY N',
      category: 'News',
      keywords: ['sky news', 'sky news uk', 'sky news arabia', 'sky news international'],
      gradient: [Color(0xFFCC0000), Color(0xFF001965)],
      iconUrl: 'https://d2n0069hmnqmmx.cloudfront.net/epgdata/1.0/newchanlogos/512/512/skychb1404.png',
    ),
    HardcodedChannel(
      id: 'al_jazeera',
      name: 'Al Jazeera English',
      short: 'AJE',
      category: 'News',
      keywords: ['al jazeera', 'al jazeera english', 'al jazeera news', 'aljazeera'],
      gradient: [Color(0xFFD4AF37), Color(0xFF1A1A1A)],
      iconUrl: 'https://dtil.tmsimg.com/assets/s159135_ld_h15_aa.png?lock=720x540',
    ),
    HardcodedChannel(
      id: 'cnbc',
      name: 'CNBC HD',
      short: 'CNBC',
      category: 'News',
      keywords: ['cnbc', 'cnbc news', 'cnbc international', 'cnbc us'],
      gradient: [Color(0xFF002B49), Color(0xFF005696)],
      iconUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/CNBC_2025.svg/960px-CNBC_2025.svg.png',
    ),
    HardcodedChannel(
      id: 'bloomberg',
      name: 'Bloomberg TV',
      short: 'BLOOM',
      category: 'News',
      keywords: ['bloomberg', 'bloomberg tv', 'bloomberg news', 'bloomberg financial'],
      gradient: [Color(0xFF000000), Color(0xFF333333)],
      iconUrl: 'https://i.imgur.com/R7FCaB5.png',
    ),
    HardcodedChannel(
      id: 'france24',
      name: 'France 24 English',
      short: 'F24',
      category: 'News',
      keywords: ['france 24', 'france 24 english', 'france 24 news'],
      gradient: [Color(0xFF002B49), Color(0xFF005696)],
      iconUrl: 'https://ltsk-cdn.s3.eu-west-1.amazonaws.com/jumpstart/Temp_Live/cdn/HLS/Channel/transparentImages/France%2024.png',
    ),

    // ── ARABIC & REGIONAL ──
    HardcodedChannel(
      id: 'mbc',
      name: 'MBC 1 HD',
      short: 'MBC1',
      category: 'Arabic',
      keywords: ['mbc', 'mbc 1', 'mbc masr', 'mbc drama', 'mbc action', 'mbc 2', 'mbc 4'],
      gradient: [Color(0xFF8E24AA), Color(0xFF1A1A1A)],
      iconUrl: 'https://i.imgur.com/CiA3plN.png',
    ),
    HardcodedChannel(
      id: 'rotana',
      name: 'Rotana Cinema HD',
      short: 'ROT',
      category: 'Arabic',
      keywords: ['rotana', 'rotana cinema', 'rotana classic', 'rotana drama', 'rotana khaleejiya'],
      gradient: [Color(0xFFE65100), Color(0xFF1A1A1A)],
      iconUrl: 'https://i.imgur.com/2zFQbQi.png',
    ),
    HardcodedChannel(
      id: 'osn',
      name: 'OSN TV HD',
      short: 'OSN',
      category: 'Arabic',
      keywords: ['osn', 'osn ya hala', 'osn series', 'osn news', 'osn pop up'],
      gradient: [Color(0xFFD500F9), Color(0xFF1A1A1A)],
      iconUrl: 'https://www.osn.com/osn/media/OSNMedia/osntv/images/common/osntv-purple-logo-hub.png',
    ),
    HardcodedChannel(
      id: 'abu_dhabi',
      name: 'Abu Dhabi Sports HD',
      short: 'AD SP',
      category: 'Arabic',
      keywords: ['abu dhabi', 'abu dhabi sports', 'ad sports', 'ad sports 1', 'ad sports 2'],
      gradient: [Color(0xFF00897B), Color(0xFF1A1A1A)],
      iconUrl: 'https://i.imgur.com/8DAriPs.png',
    ),
    HardcodedChannel(
      id: 'dubai_tv',
      name: 'Dubai Sports HD',
      short: 'DXB SP',
      category: 'Arabic',
      keywords: ['dubai sports', 'dubai tv', 'dubai one', 'dubai sports 1', 'dubai sports 2'],
      gradient: [Color(0xFF039BE5), Color(0xFF1A1A1A)],
      iconUrl: 'https://i.imgur.com/Dj16oKL.png',
    ),
    HardcodedChannel(
      id: 'alarabiya',
      name: 'Al Arabiya News',
      short: 'ARAB',
      category: 'Arabic',
      keywords: ['al arabiya', 'alarabiya', 'alhadath', 'al hadath', 'arabiya news'],
      gradient: [Color(0xFF5E35B1), Color(0xFF1A1A1A)],
      iconUrl: 'https://shahid.mbc.net/mediaObject/a4c125db-ede8-4970-9eed-963948c78651?height=auto&width=512&croppingPoint=&version=1&type=png',
    ),

    // ── DISCOVERY & DOCUMENTARIES ──
    HardcodedChannel(
      id: 'discovery',
      name: 'Discovery Channel HD',
      short: 'DISC',
      category: 'Discovery',
      keywords: ['discovery', 'discovery channel', 'discovery science', 'discovery turbo'],
      gradient: [Color(0xFF006699), Color(0xFF1A1A1A)],
      iconUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/usa/discovery-us.png',
      backdropUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/usa/discovery-us.png',
    ),
    HardcodedChannel(
      id: 'nat_geo',
      name: 'National Geographic HD',
      short: 'NATGEO',
      category: 'Discovery',
      keywords: ['national geographic', 'nat geo', 'nat geo wild', 'nat geo people'],
      gradient: [Color(0xFFFFD700), Color(0xFF1A1A1A)],
      iconUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Natgeologo.svg/960px-Natgeologo.svg.png',
    ),
    HardcodedChannel(
      id: 'history',
      name: 'History Channel HD',
      short: 'HIST',
      category: 'Discovery',
      keywords: ['history', 'history channel', 'history 2', 'h2'],
      gradient: [Color(0xFFC59B27), Color(0xFF1A1A1A)],
      iconUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/usa/history-us.png',
      backdropUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/usa/history-us.png',
    ),
    HardcodedChannel(
      id: 'animal_planet',
      name: 'Animal Planet HD',
      short: 'ANIMAL',
      category: 'Discovery',
      keywords: ['animal planet', 'animal planet hd'],
      gradient: [Color(0xFF43A047), Color(0xFF1A1A1A)],
      iconUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/2018_Animal_Planet_logo.svg/960px-2018_Animal_Planet_logo.svg.png',
    ),

    // ── KIDS & FAMILY ──
    HardcodedChannel(
      id: 'cartoon_network',
      name: 'Cartoon Network HD',
      short: 'CN',
      category: 'Kids',
      keywords: ['cartoon network', 'cn', 'boomerang'],
      gradient: [Color(0xFF000000), Color(0xFF00AEEF)],
      iconUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/Cartoon_Network_2010_logo.svg/960px-Cartoon_Network_2010_logo.svg.png',
    ),
    HardcodedChannel(
      id: 'disney',
      name: 'Disney Channel HD',
      short: 'DISNEY',
      category: 'Kids',
      keywords: ['disney', 'disney channel', 'disney xd', 'disney junior'],
      gradient: [Color(0xFF005696), Color(0xFF00A3E0)],
      iconUrl: 'https://upload.wikimedia.org/wikipedia/commons/b/bb/Disney_Channel_2014_HD.png',
    ),
    HardcodedChannel(
      id: 'nickelodeon',
      name: 'Nickelodeon HD',
      short: 'NICK',
      category: 'Kids',
      keywords: ['nickelodeon', 'nick', 'nick jr', 'nicktoons'],
      gradient: [Color(0xFFFF6D00), Color(0xFF1A1A1A)],
      iconUrl: 'https://i.imgur.com/E84jnP8.png',
    ),
    HardcodedChannel(
      id: 'spacetoon',
      name: 'Spacetoon HD',
      short: 'SPACE',
      category: 'Kids',
      keywords: ['spacetoon', 'space toon', 'spacetoon go'],
      gradient: [Color(0xFF00ACC1), Color(0xFF1A1A1A)],
      iconUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-arab-emirates/spacetoon-ae.png',
      backdropUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-arab-emirates/spacetoon-ae.png',
    ),

    // ── QUICK CHANNELS — US REGION ──
    HardcodedChannel(
      id: 'abc_us',
      name: 'ABC News Live',
      short: 'ABC',
      category: 'US',
      keywords: ['abc news', 'abc news live', 'abc us news'],
      gradient: [Color(0xFF000000), Color(0xFF002D62)],
      iconUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/ABCNewsLive.svg/960px-ABCNewsLive.svg.png',
    ),
    HardcodedChannel(
      id: 'cbs_us',
      name: 'CBS News 24/7',
      short: 'CBS',
      category: 'US',
      keywords: ['cbs news', 'cbs news 24/7', 'cbs us'],
      gradient: [Color(0xFF000000), Color(0xFF7F2B9B)],
      iconUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/CBS_News_2017.svg/960px-CBS_News_2017.svg.png',
    ),
    HardcodedChannel(
      id: 'nbc_us',
      name: 'NBC News Now',
      short: 'NBC',
      category: 'US',
      keywords: ['nbc news', 'nbc news now', 'nbc us'],
      gradient: [Color(0xFF0078D7), Color(0xFF000000)],
      iconUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/NBC_Universal_logo_2022.svg/960px-NBC_Universal_logo_2022.svg.png',
    ),
    HardcodedChannel(
      id: 'weather_channel',
      name: 'The Weather Channel',
      short: 'TWC',
      category: 'US',
      keywords: ['weather channel', 'twc', 'weather'],
      gradient: [Color(0xFF003366), Color(0xFF00AAEE)],
      iconUrl: 'https://i.imgur.com/7y5gP6N.png',
    ),
    HardcodedChannel(
      id: 'fox_weather',
      name: 'Fox Weather',
      short: 'FWX',
      category: 'US',
      keywords: ['fox weather', 'weather fox'],
      gradient: [Color(0xFF003366), Color(0xFFCC0000)],
      iconUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/usa/fox-weather-us.png',
      backdropUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/usa/fox-weather-us.png',
    ),
    HardcodedChannel(
      id: 'cnbc_us',
      name: 'CNBC',
      short: 'CNBC',
      category: 'US',
      keywords: ['cnbc', 'cnbc news', 'cnbc us'],
      gradient: [Color(0xFF002B49), Color(0xFF005696)],
      iconUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/CNBC_2025.svg/960px-CNBC_2025.svg.png',
    ),
    HardcodedChannel(
      id: 'foxbusiness',
      name: 'Fox Business',
      short: 'FBN',
      category: 'US',
      keywords: ['fox business', 'fnc business'],
      gradient: [Color(0xFF003366), Color(0xFFCC0000)],
      iconUrl: 'https://i.imgur.com/KqJ4b1P.png',
    ),
    HardcodedChannel(
      id: 'court_tv',
      name: 'Court TV',
      short: 'COURT',
      category: 'US',
      keywords: ['court tv', 'court'],
      gradient: [Color(0xFF1A1A1A), Color(0xFFD4AF37)],
      iconUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/usa/court-tv-us.png',
      backdropUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/usa/court-tv-us.png',
    ),
    HardcodedChannel(
      id: 'newsmax',
      name: 'Newsmax TV',
      short: 'NEWSM',
      category: 'US',
      keywords: ['newsmax', 'newsmax tv'],
      gradient: [Color(0xFF003366), Color(0xFFCC0000)],
      iconUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/usa/newsmax-us.png',
      backdropUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/usa/newsmax-us.png',
    ),
    HardcodedChannel(
      id: 'newsnation',
      name: 'NewsNation',
      short: 'NSN',
      category: 'US',
      keywords: ['newsnation', 'news nation'],
      gradient: [Color(0xFF003366), Color(0xFF0066CC)],
      iconUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/usa/newsnation-us.png',
      backdropUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/usa/newsnation-us.png',
    ),
    HardcodedChannel(
      id: 'oan',
      name: 'One America News (OAN)',
      short: 'OAN',
      category: 'US',
      keywords: ['one america news', 'oan'],
      gradient: [Color(0xFFCC0000), Color(0xFF003366)],
      iconUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/usa/oan-us.png',
      backdropUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/usa/oan-us.png',
    ),
    HardcodedChannel(
      id: 'real_americas_voice',
      name: 'Real America\'s Voice',
      short: 'RAV',
      category: 'US',
      keywords: ['real americas voice', 'rav', 'truth'],
      gradient: [Color(0xFF8B0000), Color(0xFF1A1A1A)],
      iconUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/usa/real-americas-voice-us.png',
      backdropUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/usa/real-americas-voice-us.png',
    ),
    HardcodedChannel(
      id: 'newsy',
      name: 'Newsy',
      short: 'NEWSY',
      category: 'US',
      keywords: ['newsy', 'newsy news'],
      gradient: [Color(0xFF0066CC), Color(0xFF003366)],
      iconUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/usa/newsy-us.png',
      backdropUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/usa/newsy-us.png',
    ),
    HardcodedChannel(
      id: 'cheddar',
      name: 'Cheddar News',
      short: 'CHED',
      category: 'US',
      keywords: ['cheddar', 'cheddar news'],
      gradient: [Color(0xFFE65100), Color(0xFF1A1A1A)],
      iconUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/usa/cheddar-us.png',
      backdropUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/usa/cheddar-us.png',
    ),
    HardcodedChannel(
      id: 'cbn_news',
      name: 'CBN News',
      short: 'CBN',
      category: 'US',
      keywords: ['cbn news', 'christian broadcasting'],
      gradient: [Color(0xFF005696), Color(0xFFD4AF37)],
      iconUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/usa/cbn-news-us.png',
      backdropUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/usa/cbn-news-us.png',
    ),

    // ── QUICK CHANNELS — UK REGION ──
    HardcodedChannel(
      id: 'bbc_one_uk',
      name: 'BBC One UK',
      short: 'BBC1',
      category: 'UK',
      keywords: ['bbc one uk', 'bbc1', 'bbc news uk'],
      gradient: [Color(0xFFBB1919), Color(0xFF1A1A1A)],
      iconUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-kingdom/bbc-one-uk.png',
      backdropUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-kingdom/bbc-one-uk.png',
    ),
    HardcodedChannel(
      id: 'itv_uk',
      name: 'ITV News',
      short: 'ITV',
      category: 'UK',
      keywords: ['itv news', 'itv', 'itv channel'],
      gradient: [Color(0xFF00AEEF), Color(0xFF005696)],
      iconUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-kingdom/itv-uk.png',
      backdropUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-kingdom/itv-uk.png',
    ),
    HardcodedChannel(
      id: 'sky_news_uk',
      name: 'Sky News UK',
      short: 'SKN',
      category: 'UK',
      keywords: ['sky news uk', 'sky news', 'gb news'],
      gradient: [Color(0xFFCC0000), Color(0xFF001965)],
      iconUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-kingdom/sky-news-uk.png',
      backdropUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-kingdom/sky-news-uk.png',
    ),
    HardcodedChannel(
      id: 'channel4_uk',
      name: 'Channel 4 News',
      short: 'C4',
      category: 'UK',
      keywords: ['channel 4', 'channel four', 'c4 news'],
      gradient: [Color(0xFFFF0066), Color(0xFF1A1A1A)],
      iconUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-kingdom/channel-4-uk.png',
      backdropUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-kingdom/channel-4-uk.png',
    ),
    HardcodedChannel(
      id: 'talktv',
      name: 'TalkTV',
      short: 'TALK',
      category: 'UK',
      keywords: ['talktv', 'talk tv'],
      gradient: [Color(0xFF00AEEF), Color(0xFF003366)],
      iconUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-kingdom/talktv-uk.png',
      backdropUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-kingdom/talktv-uk.png',
    ),
    HardcodedChannel(
      id: 'lbc',
      name: 'LBC News',
      short: 'LBC',
      category: 'UK',
      keywords: ['lbc', 'lbc news'],
      gradient: [Color(0xFFCC0000), Color(0xFF003366)],
      iconUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-kingdom/lbc-uk.png',
      backdropUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-kingdom/lbc-uk.png',
    ),
    HardcodedChannel(
      id: 'stv_news',
      name: 'STV News',
      short: 'STV',
      category: 'UK',
      keywords: ['stv news', 'scottish tv'],
      gradient: [Color(0xFF0066CC), Color(0xFF003366)],
      iconUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-kingdom/stv-uk.png',
      backdropUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-kingdom/stv-uk.png',
    ),
    HardcodedChannel(
      id: 'gb_news',
      name: 'GB News',
      short: 'GB',
      category: 'UK',
      keywords: ['gb news', 'great britain news'],
      gradient: [Color(0xFF003366), Color(0xFFFFD700)],
      iconUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-kingdom/gb-news-uk.png',
      backdropUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-kingdom/gb-news-uk.png',
    ),

    // ── QUICK CHANNELS — CANADA REGION ──
    HardcodedChannel(
      id: 'cbc_news',
      name: 'CBC News',
      short: 'CBC',
      category: 'CA',
      keywords: ['cbc news', 'cbc', 'canadian broadcasting'],
      gradient: [Color(0xFFCC0000), Color(0xFF003366)],
      iconUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/canada/cbc-news-ca.png',
      backdropUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/canada/cbc-news-ca.png',
    ),
    HardcodedChannel(
      id: 'ctv_news',
      name: 'CTV News Channel',
      short: 'CTV',
      category: 'CA',
      keywords: ['ctv news', 'ctv news channel'],
      gradient: [Color(0xFF003366), Color(0xFFCC0000)],
      iconUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/canada/ctv-news-ca.png',
      backdropUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/canada/ctv-news-ca.png',
    ),
    HardcodedChannel(
      id: 'tsn',
      name: 'TSN Sportsnet',
      short: 'TSN',
      category: 'CA',
      keywords: ['tsn', 'tsn sports', 'sportsnet', 'sportsnet world'],
      gradient: [Color(0xFFCC0000), Color(0xFF003366)],
      iconUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/canada/tsn-ca.png',
      backdropUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/canada/tsn-ca.png',
    ),
    HardcodedChannel(
      id: 'crave',
      name: 'Crave',
      short: 'CRAVE',
      category: 'CA',
      keywords: ['crave', 'crave tv'],
      gradient: [Color(0xFF1A1A1A), Color(0xFFCC0000)],
      iconUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/canada/crave-ca.png',
      backdropUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/canada/crave-ca.png',
    ),
    HardcodedChannel(
      id: 'global_ca',
      name: 'Global News',
      short: 'GLOBAL',
      category: 'CA',
      keywords: ['global news', 'global tv canada'],
      gradient: [Color(0xFF003366), Color(0xFFD4AF37)],
      iconUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/canada/global-news-ca.png',
      backdropUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/canada/global-news-ca.png',
    ),
    HardcodedChannel(
      id: 'canadian_news',
      name: 'Canadian News',
      short: 'CAN',
      category: 'CA',
      keywords: ['canadian news', 'canada news'],
      gradient: [Color(0xFFCC0000), Color(0xFFFFFFFF)],
      iconUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/canada/canadian-news-ca.png',
      backdropUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/canada/canadian-news-ca.png',
    ),

    // ── QUICK CHANNELS — BAY AREA ──
    HardcodedChannel(
      id: 'ktvu',
      name: 'KTVU Fox 2',
      short: 'KTVU',
      category: 'Bay Area',
      keywords: ['ktvu', 'fox 2 bay area'],
      gradient: [Color(0xFF003366), Color(0xFFFFD700)],
      iconUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/usa/ktvu-us.png',
      backdropUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/usa/ktvu-us.png',
    ),
    HardcodedChannel(
      id: 'kpix',
      name: 'KPIX 5 CBS',
      short: 'KPIX',
      category: 'Bay Area',
      keywords: ['kpix', 'cbs bay area'],
      gradient: [Color(0xFF7F2B9B), Color(0xFF000000)],
      iconUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/usa/kpix-us.png',
      backdropUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/usa/kpix-us.png',
    ),
    HardcodedChannel(
      id: 'kgov',
      name: 'KGO 7 ABC',
      short: 'KGO',
      category: 'Bay Area',
      keywords: ['kgov', 'abc bay area'],
      gradient: [Color(0xFF000000), Color(0xFF002D62)],
      iconUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/usa/kgov-us.png',
      backdropUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/usa/kgov-us.png',
    ),
    HardcodedChannel(
      id: 'kron',
      name: 'KRON 4',
      short: 'KRON',
      category: 'Bay Area',
      keywords: ['kron', 'kron 4'],
      gradient: [Color(0xFFCC0000), Color(0xFF003366)],
      iconUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/usa/kron-us.png',
      backdropUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/usa/kron-us.png',
    ),
    HardcodedChannel(
      id: 'nbc_bay_area',
      name: 'NBC Bay Area',
      short: 'NBCBA',
      category: 'Bay Area',
      keywords: ['nbc bay area', 'kcra', 'bay area news'],
      gradient: [Color(0xFF0078D7), Color(0xFF000000)],
      iconUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/usa/nbc-bay-area-us.png',
      backdropUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/usa/nbc-bay-area-us.png',
    ),

    // ── QUICK CHANNELS — INTERNATIONAL SPORTS ──
    HardcodedChannel(
      id: 'willow_cric',
      name: 'Willow Cricket',
      short: 'WIL',
      category: 'Int. Sports',
      keywords: ['willow', 'willow cricket', 'cricket'],
      gradient: [Color(0xFF0066CC), Color(0xFF003366)],
      iconUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/usa/willow-cricket-us.png',
      backdropUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/usa/willow-cricket-us.png',
    ),
    HardcodedChannel(
      id: 'fox_soccer_plus',
      name: 'Fox Soccer Plus',
      short: 'FSP',
      category: 'Int. Sports',
      keywords: ['fox soccer plus', 'fsplus', 'fox sports soccer'],
      gradient: [Color(0xFF003366), Color(0xFF0066CC)],
      iconUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/usa/fox-soccer-plus-us.png',
      backdropUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/usa/fox-soccer-plus-us.png',
    ),
    HardcodedChannel(
      id: 'goltv',
      name: 'GolTV',
      short: 'GOL',
      category: 'Int. Sports',
      keywords: ['goltv', 'gol tv'],
      gradient: [Color(0xFF0066CC), Color(0xFF00AA00)],
      iconUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/usa/goltv-us.png',
      backdropUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/usa/goltv-us.png',
    ),
    HardcodedChannel(
      id: 'tvg',
      name: 'TVG',
      short: 'TVG',
      category: 'Int. Sports',
      keywords: ['tvg', 'tvg network'],
      gradient: [Color(0xFFD4AF37), Color(0xFF1A1A1A)],
      iconUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/usa/tvg-us.png',
      backdropUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/usa/tvg-us.png',
    ),
    HardcodedChannel(
      id: 'stadium',
      name: 'Stadium',
      short: 'STD',
      category: 'Int. Sports',
      keywords: ['stadium', 'stadium sports'],
      gradient: [Color(0xFFCC0000), Color(0xFF003366)],
      iconUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/usa/stadium-us.png',
      backdropUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/usa/stadium-us.png',
    ),
    HardcodedChannel(
      id: 'fight_network',
      name: 'Fight Network',
      short: 'FIGHT',
      category: 'Int. Sports',
      keywords: ['fight network', 'combat sports'],
      gradient: [Color(0xFFD20A0A), Color(0xFF1A1A1A)],
      iconUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/usa/fight-network-us.png',
      backdropUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/usa/fight-network-us.png',
    ),
    HardcodedChannel(
      id: 'espn_caribbean',
      name: 'ESPN Caribbean',
      short: 'ESPNC',
      category: 'Int. Sports',
      keywords: ['espn caribbean', 'espn caribe'],
      gradient: [Color(0xFFCC0000), Color(0xFF003087)],
      iconUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/international/espn-caribbean.png',
      backdropUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/international/espn-caribbean.png',
    ),
    HardcodedChannel(
      id: 'tudn',
      name: 'TUDN',
      short: 'TUDN',
      category: 'Int. Sports',
      keywords: ['tudn', 'televisa univision'],
      gradient: [Color(0xFF003087), Color(0xFFCC0000)],
      iconUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/mexico/tudn-mx.png',
      backdropUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/mexico/tudn-mx.png',
    ),
    HardcodedChannel(
      id: 'viaplay_sports',
      name: 'Viaplay Sports',
      short: 'VIA',
      category: 'Int. Sports',
      keywords: ['viaplay', 'viaplay sports', 'viaplay football'],
      gradient: [Color(0xFFFF6D00), Color(0xFF1A1A1A)],
      iconUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/sweden/viaplay-sports-se.png',
      backdropUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/sweden/viaplay-sports-se.png',
    ),
    HardcodedChannel(
      id: 'eleven_sports',
      name: 'Eleven Sports',
      short: 'ELE',
      category: 'Int. Sports',
      keywords: ['eleven sports', 'eleven'],
      gradient: [Color(0xFF003366), Color(0xFFCC0000)],
      iconUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/belgium/eleven-sports-be.png',
      backdropUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/belgium/eleven-sports-be.png',
    ),
    HardcodedChannel(
      id: 'setanta_sports',
      name: 'Setanta Sports',
      short: 'SET',
      category: 'Int. Sports',
      keywords: ['setanta', 'setanta sports'],
      gradient: [Color(0xFF0066CC), Color(0xFF00AA00)],
      iconUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/ireland/setanta-sports-ie.png',
      backdropUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/ireland/setanta-sports-ie.png',
    ),
    HardcodedChannel(
      id: 'sport_klub',
      name: 'Sport Klub',
      short: 'SKL',
      category: 'Int. Sports',
      keywords: ['sport klub', 'sportklub'],
      gradient: [Color(0xFFCC0000), Color(0xFF003366)],
      iconUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/serbia/sport-klub-rs.png',
      backdropUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/serbia/sport-klub-rs.png',
    ),
    HardcodedChannel(
      id: 'sky_sport_italia',
      name: 'Sky Sport Italia',
      short: 'SKYI',
      category: 'Int. Sports',
      keywords: ['sky sport italia', 'sky sport italy'],
      gradient: [Color(0xFF001965), Color(0xFFCC0000)],
      iconUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/italy/sky-sport-italia-it.png',
      backdropUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/italy/sky-sport-italia-it.png',
    ),
    HardcodedChannel(
      id: 'sky_sport_de',
      name: 'Sky Sport DE',
      short: 'SKYDE',
      category: 'Int. Sports',
      keywords: ['sky sport germany', 'sky sport de', 'sky sport deutschland'],
      gradient: [Color(0xFF001965), Color(0xFFCC0000)],
      iconUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/germany/sky-sport-de.png',
      backdropUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/germany/sky-sport-de.png',
    ),
    HardcodedChannel(
      id: 'rai_sport',
      name: 'RAI Sport',
      short: 'RAI',
      category: 'Int. Sports',
      keywords: ['rai sport', 'rai sports'],
      gradient: [Color(0xFF0066CC), Color(0xFFCC0000)],
      iconUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/italy/rai-sport-it.png',
      backdropUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/italy/rai-sport-it.png',
    ),
    HardcodedChannel(
      id: 'rmc_sport',
      name: 'RMC Sport',
      short: 'RMC',
      category: 'Int. Sports',
      keywords: ['rmc sport', 'rmc'],
      gradient: [Color(0xFFCC0000), Color(0xFF003366)],
      iconUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/france/rmc-sport-fr.png',
      backdropUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/france/rmc-sport-fr.png',
    ),
    HardcodedChannel(
      id: 'canal_plus_sport',
      name: 'Canal+ Sport',
      short: 'C+SP',
      category: 'Int. Sports',
      keywords: ['canal plus sport', 'canal+ sport', 'c+ sport'],
      gradient: [Color(0xFF003366), Color(0xFFCC0000)],
      iconUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/france/canal-plus-sport-fr.png',
      backdropUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/france/canal-plus-sport-fr.png',
    ),
    HardcodedChannel(
      id: 'nova_sports',
      name: 'Nova Sports',
      short: 'NOVA',
      category: 'Int. Sports',
      keywords: ['nova sports', 'nova sport'],
      gradient: [Color(0xFF00AEEF), Color(0xFF003366)],
      iconUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/greece/nova-sports-gr.png',
      backdropUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/greece/nova-sports-gr.png',
    ),
    HardcodedChannel(
      id: 'star_sports_in',
      name: 'Star Sports India',
      short: 'SSI',
      category: 'Int. Sports',
      keywords: ['star sports india', 'star sports', 'star sports 1', 'star sports 2'],
      gradient: [Color(0xFF003366), Color(0xFFFFD700)],
      iconUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/india/star-sports-in.png',
      backdropUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/india/star-sports-in.png',
    ),
    HardcodedChannel(
      id: 'sony_sports_in',
      name: 'Sony Sports India',
      short: 'SONY',
      category: 'Int. Sports',
      keywords: ['sony sports', 'sony six', 'sony sports six'],
      gradient: [Color(0xFF005696), Color(0xFFCC0000)],
      iconUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/india/sony-sports-in.png',
      backdropUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/india/sony-sports-in.png',
    ),
    HardcodedChannel(
      id: 'match_tv',
      name: 'Match TV',
      short: 'MATCH',
      category: 'Int. Sports',
      keywords: ['match tv', 'match!', 'russian sports'],
      gradient: [Color(0xFF003366), Color(0xFFCC0000)],
      iconUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/russia/match-tv-ru.png',
      backdropUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/russia/match-tv-ru.png',
    ),
    HardcodedChannel(
      id: 'eurosport_eu',
      name: 'Eurosport Europe',
      short: 'EURO',
      category: 'Int. Sports',
      keywords: ['eurosport europe', 'eurosport fr', 'eurosport de'],
      gradient: [Color(0xFF002B49), Color(0xFF005696)],
      iconUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/international/eurosport.png',
      backdropUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/international/eurosport.png',
    ),

    // ── QUICK CHANNELS — GLOBAL NEWS EXTENDED ──
    HardcodedChannel(
      id: 'i24_news',
      name: 'i24 News',
      short: 'I24',
      category: 'News',
      keywords: ['i24 news', 'i24news'],
      gradient: [Color(0xFF005696), Color(0xFF00AAEE)],
      iconUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/israel/i24-news-il.png',
      backdropUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/israel/i24-news-il.png',
    ),
    HardcodedChannel(
      id: 'cgtn',
      name: 'CGTN',
      short: 'CGTN',
      category: 'News',
      keywords: ['cgtn', 'china global television'],
      gradient: [Color(0xFFCC0000), Color(0xFFFFD700)],
      iconUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/china/cgtn-cn.png',
      backdropUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/china/cgtn-cn.png',
    ),
    HardcodedChannel(
      id: 'nhk_world',
      name: 'NHK World Japan',
      short: 'NHK',
      category: 'News',
      keywords: ['nhk world', 'nhk japan', 'nhk world japan'],
      gradient: [Color(0xFF0066CC), Color(0xFFCC0000)],
      iconUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/japan/nhk-world-jp.png',
      backdropUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/japan/nhk-world-jp.png',
    ),
    HardcodedChannel(
      id: 'dubai_one',
      name: 'Dubai One',
      short: 'DXB1',
      category: 'News',
      keywords: ['dubai one', 'dubai tv'],
      gradient: [Color(0xFF039BE5), Color(0xFF1A1A1A)],
      iconUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-arab-emirates/dubai-one-ae.png',
      backdropUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-arab-emirates/dubai-one-ae.png',
    ),
    HardcodedChannel(
      id: 'sky_news_au',
      name: 'Sky News Australia',
      short: 'SKYAU',
      category: 'News',
      keywords: ['sky news australia', 'sky news au'],
      gradient: [Color(0xFFCC0000), Color(0xFF001965)],
      iconUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/australia/sky-news-au.png',
      backdropUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/australia/sky-news-au.png',
    ),
    HardcodedChannel(
      id: 'fox_news_au',
      name: 'Fox News Australia',
      short: 'FOXAU',
      category: 'News',
      keywords: ['fox news australia', 'fox au'],
      gradient: [Color(0xFF003366), Color(0xFFCC0000)],
      iconUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/australia/fox-news-au.png',
      backdropUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/australia/fox-news-au.png',
    ),
    HardcodedChannel(
      id: 'abc_news_au',
      name: 'ABC News Australia',
      short: 'ABCAU',
      category: 'News',
      keywords: ['abc news australia', 'abc au'],
      gradient: [Color(0xFF000000), Color(0xFF0066CC)],
      iconUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/australia/abc-news-au.png',
      backdropUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/australia/abc-news-au.png',
    ),

    // ── QUICK CHANNELS — PREMIUM MOVIES EXTENDED ──
    HardcodedChannel(
      id: 'mgm_plus',
      name: 'MGM+',
      short: 'MGM+',
      category: 'Movies',
      keywords: ['mgm plus', 'mgm+', 'mgm premium'],
      gradient: [Color(0xFFD4AF37), Color(0xFF1A1A1A)],
      iconUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/usa/mgm-plus-us.png',
      backdropUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/usa/mgm-plus-us.png',
    ),
    HardcodedChannel(
      id: 'tmc',
      name: 'TMC (The Movie Channel)',
      short: 'TMC',
      category: 'Movies',
      keywords: ['tmc', 'the movie channel', 'movie channel'],
      gradient: [Color(0xFF003366), Color(0xFFD4AF37)],
      iconUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/usa/tmc-us.png',
      backdropUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/usa/tmc-us.png',
    ),
    HardcodedChannel(
      id: 'fxm',
      name: 'FXM',
      short: 'FXM',
      category: 'Movies',
      keywords: ['fxm', 'fx movie channel'],
      gradient: [Color(0xFF212121), Color(0xFF424242)],
      iconUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/usa/fxm-us.png',
      backdropUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/usa/fxm-us.png',
    ),
    HardcodedChannel(
      id: 'canadian_premium',
      name: 'Canadian Premium Movies',
      short: 'CANM',
      category: 'Movies',
      keywords: ['canadian premium', 'super channel', 'cinemax ca'],
      gradient: [Color(0xFFCC0000), Color(0xFF003366)],
      iconUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/canada/super-channel-ca.png',
      backdropUrl: 'https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/canada/super-channel-ca.png',
    ),
  ];
}
