#!/usr/bin/env bash
# =============================================================================
#  PlayTorrio Nuvio Addon — NVIDIA Shield Pro (Termux) Auto-Start Setup
#
#  Makes the addon server start automatically whenever the Shield boots,
#  and keeps it alive even when the Termux app is closed.
#
#  Requirements:
#    1. Termux installed (from F-Droid, NOT Play Store)
#    2. Termux:Boot installed (from F-Droid)
#       https://f-droid.org/packages/com.termux.boot/
#
#  Usage (run inside Termux on your Shield):
#    bash pipeline/install_termux_service.sh
# =============================================================================

set -e
cd "$(cd "$(dirname "$0")/.." && pwd)"
PROJECT_ROOT="$(pwd)"

echo ""
echo "============================================================"
echo "  🛡️  PlayTorrio — NVIDIA Shield (Termux) Auto-Start Setup"
echo "============================================================"
echo ""

# ── Check Termux:Boot ─────────────────────────────────────────────────────────
BOOT_DIR="$HOME/.termux/boot"
if [ ! -d "$BOOT_DIR" ]; then
    echo " Creating ~/.termux/boot/ ..."
    echo " NOTE: Install 'Termux:Boot' from F-Droid for this to work."
    echo "       https://f-droid.org/packages/com.termux.boot/"
    mkdir -p "$BOOT_DIR"
fi

# ── Find Dart ─────────────────────────────────────────────────────────────────
DART_EXE=""
if   command -v dart &>/dev/null; then DART_EXE="dart"
elif [ -f "$PREFIX/bin/dart" ];   then DART_EXE="$PREFIX/bin/dart"
fi

if [ -z "$DART_EXE" ]; then
    echo ""
    echo " Installing Dart in Termux..."
    pkg update -y && pkg install -y dart git curl
    DART_EXE="dart"
fi

echo " Dart found: $DART_EXE ✓"

# ── Run first-time setup ──────────────────────────────────────────────────────
echo ""
echo " Running first-time setup..."
"$DART_EXE" run tool/setup.dart

# ── Try to compile a native binary for fastest boot ──────────────────────────
COMPILED_BIN="$PROJECT_ROOT/playtorrio-addon"
if [ ! -f "$COMPILED_BIN" ]; then
    echo ""
    echo " Compiling native binary (one-time, takes ~2 min)..."
    "$DART_EXE" compile exe bin/server.dart -o playtorrio-addon
    if [ -f "$COMPILED_BIN" ]; then
        chmod +x "$COMPILED_BIN"
        echo " Native binary compiled ✓"
    fi
fi

# ── Write boot script ─────────────────────────────────────────────────────────
BOOT_SCRIPT="$BOOT_DIR/playtorrio-addon.sh"
cat > "$BOOT_SCRIPT" << BOOTSCRIPT
#!/data/data/com.termux/files/usr/bin/bash
# Auto-generated by install_termux_service.sh
# Starts PlayTorrio Nuvio Addon on Shield boot.

# Keep Termux awake (prevents Android from killing the process)
termux-wake-lock

cd "$PROJECT_ROOT"

# Wait a moment for network to be ready after boot
sleep 8

if [ -f "$COMPILED_BIN" ]; then
    exec "$COMPILED_BIN"
else
    exec "$DART_EXE" run bin/server.dart
fi
BOOTSCRIPT

chmod +x "$BOOT_SCRIPT"
echo ""
echo " Boot script installed: $BOOT_SCRIPT ✓"

# ── Write a keep-alive run script ─────────────────────────────────────────────
# This wraps the server in a loop so it auto-restarts on crash
KEEPALIVE="$PROJECT_ROOT/run_forever.sh"
cat > "$KEEPALIVE" << 'FOREVER'
#!/usr/bin/env bash
# Runs the PlayTorrio addon server forever, restarting on crash.
cd "$(cd "$(dirname "$0")" && pwd)"
termux-wake-lock
echo "[run_forever] Starting PlayTorrio addon server (auto-restart on crash)..."
while true; do
    if [ -f "./playtorrio-addon" ]; then
        ./playtorrio-addon || true
    else
        dart run bin/server.dart || true
    fi
    echo "[run_forever] Server stopped. Restarting in 5 seconds..."
    sleep 5
done
FOREVER

chmod +x "$KEEPALIVE"

# Update the boot script to use run_forever
cat > "$BOOT_SCRIPT" << BOOTSCRIPT2
#!/data/data/com.termux/files/usr/bin/bash
# Auto-generated by install_termux_service.sh
termux-wake-lock
sleep 8
exec bash "$PROJECT_ROOT/run_forever.sh"
BOOTSCRIPT2
chmod +x "$BOOT_SCRIPT"

# ── Set up daily auto-update (cron via Termux) ────────────────────────────────
echo ""
echo " Setting up daily 4 AM auto-update via cron..."
pkg install -y cronie 2>/dev/null || true
CRON_CMD="0 4 * * * bash $PROJECT_ROOT/pipeline/update.sh >> $PROJECT_ROOT/logs/update.log 2>&1"
# Add to crontab only if not already there
if ! (crontab -l 2>/dev/null | grep -q "playtorrio"); then
    (crontab -l 2>/dev/null; echo "$CRON_CMD") | crontab -
    echo " Cron job added ✓"
else
    echo " Cron job already exists ✓"
fi

# Ensure logs dir exists
mkdir -p "$PROJECT_ROOT/logs"

# ── Print LAN IP ──────────────────────────────────────────────────────────────
LAN_IP=$(ip -4 addr show | grep -oP '(?<=inet\s)\d+\.\d+\.\d+\.\d+' \
         | grep -v '127\.' | grep -v '169\.254\.' | head -1 2>/dev/null || echo "YOUR-SHIELD-IP")

echo ""
echo "============================================================"
echo " ✅ Shield auto-start configured!"
echo ""
echo " The addon will start automatically every time"
echo " your NVIDIA Shield boots."
echo ""
echo " To start now without rebooting:"
echo "   bash run_forever.sh"
echo ""
echo " Install this URL in Nuvio (from any LAN device):"
echo "   http://$LAN_IP:7000/manifest.json"
echo ""
echo " Useful commands:"
echo "   Stop server:    pkill -f playtorrio-addon"
echo "   View logs:      tail -f logs/update.log"
echo "   Update now:     bash pipeline/update.sh"
echo "============================================================"
echo ""
